name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Build on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install root dependencies
        run: npm ci
      
      - name: Install client dependencies
        run: cd client && npm ci
      
      - name: Install server dependencies
        run: cd server && npm ci
      
      - name: Clean build artifacts
        run: |
          rm -rf client/out
          rm -rf server/out
          rm -rf *.tsbuildinfo
          rm -rf client/*.tsbuildinfo
          rm -rf server/*.tsbuildinfo
      
      - name: Compile TypeScript
        run: npm run compile
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-node-${{ matrix.node-version }}
          path: |
            client/out
            server/out
          retention-days: 7

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install root dependencies
        run: npm ci
      
      - name: Install client dependencies
        run: cd client && npm ci
      
      - name: Install server dependencies
        run: cd server && npm ci
      
      - name: Run ESLint
        run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install root dependencies
        run: npm ci
      
      - name: Install client dependencies
        run: cd client && npm ci
      
      - name: Install server dependencies
        run: cd server && npm ci
      
      - name: Clean build artifacts
        run: |
          rm -rf client/out
          rm -rf server/out
          rm -rf *.tsbuildinfo
          rm -rf client/*.tsbuildinfo
          rm -rf server/*.tsbuildinfo
      
      - name: Compile TypeScript
        run: npm run compile
      
      - name: Run tests (Linux)
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      
      - name: Run tests (Windows/macOS)
        run: npm test
        if: runner.os != 'Linux'
